server:
  port: 9003
spring:
  application:
    name: ihrm-social-securitys #指定服务名
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://116.62.26.142:3306/ihrm?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT
    username: root
    password: LYZhi0806!
  jpa:
    database: MySQL
    show-sql: true
    open-in-view: true
  redis:
    host: 116.62.26.142
    port: 6379
dubbo:
  protocol:
    name: dubbo
    port: 12342
    serialization: kryo
  registry:
    address: zookeeper://116.62.26.142:2181
    register: true
  application:
    name: ihrm-social-securitys






